# Generated by Django 2.1.5 on 2019-02-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190220_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_edit_books', 'Create, update, delete'),)},
        ),
    ]
